
package fr.treeptik.clientservice.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManagerWebSeviceService", targetNamespace = "http://webservice.service.treeptik.fr/", wsdlLocation = "http://localhost:8080/template-JSF-CDI-EJB/ManagerWebSevice?wsdl")
public class ManagerWebSeviceService
    extends Service
{

    private final static URL MANAGERWEBSEVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGERWEBSEVICESERVICE_EXCEPTION;
    private final static QName MANAGERWEBSEVICESERVICE_QNAME = new QName("http://webservice.service.treeptik.fr/", "ManagerWebSeviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/template-JSF-CDI-EJB/ManagerWebSevice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGERWEBSEVICESERVICE_WSDL_LOCATION = url;
        MANAGERWEBSEVICESERVICE_EXCEPTION = e;
    }

    public ManagerWebSeviceService() {
        super(__getWsdlLocation(), MANAGERWEBSEVICESERVICE_QNAME);
    }

    public ManagerWebSeviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGERWEBSEVICESERVICE_QNAME, features);
    }

    public ManagerWebSeviceService(URL wsdlLocation) {
        super(wsdlLocation, MANAGERWEBSEVICESERVICE_QNAME);
    }

    public ManagerWebSeviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGERWEBSEVICESERVICE_QNAME, features);
    }

    public ManagerWebSeviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerWebSeviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManagerWebSevice
     */
    @WebEndpoint(name = "ManagerWebSevicePort")
    public ManagerWebSevice getManagerWebSevicePort() {
        return super.getPort(new QName("http://webservice.service.treeptik.fr/", "ManagerWebSevicePort"), ManagerWebSevice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagerWebSevice
     */
    @WebEndpoint(name = "ManagerWebSevicePort")
    public ManagerWebSevice getManagerWebSevicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.service.treeptik.fr/", "ManagerWebSevicePort"), ManagerWebSevice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGERWEBSEVICESERVICE_EXCEPTION!= null) {
            throw MANAGERWEBSEVICESERVICE_EXCEPTION;
        }
        return MANAGERWEBSEVICESERVICE_WSDL_LOCATION;
    }

}
